const glow=document.getElementById('cursor-glow');const stage=document.getElementById('hero-stage');document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px');if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}if(stage){const r=stage.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;stage.style.transform=`perspective(900px) rotateY(${x*5}deg) rotateX(${-y*5}deg)`}});const menu=document.getElementById('menu');const nav=document.querySelector('.nav-links');menu?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.reveal').forEach(el=>new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:.12}).observe(el));
const toast=document.getElementById('toast');function showToast(t){if(!toast)return;toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}document.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>showToast(b.dataset.toast)));
const modal=document.getElementById('game-modal'),area=document.getElementById('game-area'),title=document.getElementById('modal-title');document.getElementById('close-modal').onclick=()=>modal.close();
function openGame(type){modal.showModal();const names={roulette:'Neon Roulette',blackjack:'Royal Blackjack',slots:'Cosmic Slots',baccarat:'Golden Baccarat'};title.textContent=names[type];if(type==='roulette')roulette();if(type==='blackjack')blackjack();if(type==='slots')slots();if(type==='baccarat')baccarat()}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openGame(b.dataset.open)));
function roulette(){area.innerHTML=`<div class="mini-game"><p>Elegí una casilla y girá la ruleta.</p><div class="result" id="rr">—</div><div class="game-controls">${[0,7,13,21,32].map(n=>`<button data-n="${n}">${n}</button>`).join('')}<button class="primary" id="spin">Girar</button></div></div>`;let pick=null;area.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{pick=b.dataset.n;document.getElementById('rr').textContent='Elegiste '+pick});document.getElementById('spin').onclick=()=>{const n=[0,7,13,21,32,4,18,29][Math.floor(Math.random()*8)];document.getElementById('rr').textContent=n+(String(n)===pick?' · ¡Coincidencia demo!':' · resultado demo')}}
function blackjack(){area.innerHTML=`<div class="mini-game"><p>Pedí cartas hasta acercarte a 21.</p><div class="result" id="bj">0</div><div class="game-controls"><button class="primary" id="hit">Pedir carta</button><button id="stand">Plantarse</button><button id="reset">Reiniciar</button></div></div>`;let total=0;document.getElementById('hit').onclick=()=>{total+=Math.floor(Math.random()*10)+2;document.getElementById('bj').textContent=total;if(total>21)showToast('Pasaste 21 — ronda demo terminada')};document.getElementById('stand').onclick=()=>showToast('Plantado en '+total+' · resultado demo');document.getElementById('reset').onclick=()=>{total=0;document.getElementById('bj').textContent=0}}
function slots(){area.innerHTML=`<div class="mini-game"><p>Tres símbolos. Una animación. Cero dinero real.</p><div class="slot-window"><span id="s1">7</span><span id="s2">7</span><span id="s3">7</span></div><button class="btn gold" id="roll">Girar 777</button></div>`;document.getElementById('roll').onclick=()=>{const a=['7','★','♦','✦'];const ids=['s1','s2','s3'];ids.forEach((id,i)=>document.getElementById(id).textContent=a[Math.floor(Math.random()*a.length)]);showToast('Resultado generado en modo demo')}}
function baccarat(){area.innerHTML=`<div class="mini-game"><p>Elegí una mano para la simulación.</p><div class="result" id="bc">—</div><div class="game-controls"><button class="primary" onclick="document.getElementById('bc').textContent=Math.random()>.5?'PLAYER':'BANKER'">Simular ronda</button></div></div>`}
const canvas=document.getElementById('scene');if(window.THREE&&canvas){const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);camera.position.z=7;const geo=new THREE.IcosahedronGeometry(2.7,2);const mat=new THREE.MeshBasicMaterial({color:0x9b72ff,wireframe:true,transparent:true,opacity:.12});const mesh=new THREE.Mesh(geo,mat);scene.add(mesh);const pts=new THREE.BufferGeometry();const p=[];for(let i=0;i<700;i++)p.push((Math.random()-.5)*18,(Math.random()-.5)*12,(Math.random()-.5)*10);pts.setAttribute('position',new THREE.Float32BufferAttribute(p,3));scene.add(new THREE.Points(pts,new THREE.PointsMaterial({color:0xf4c96b,size:.018,transparent:true,opacity:.65})));let tx=0,ty=0;addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*.8;ty=(e.clientY/innerHeight-.5)*.5});function loop(){requestAnimationFrame(loop);mesh.rotation.x+=.0009;mesh.rotation.y+=.0015;mesh.rotation.x+=(ty-mesh.rotation.x)*.008;mesh.rotation.z+=(tx-mesh.rotation.z)*.008;renderer.render(scene,camera)}loop();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
